#!/bin/bash
if [[ $* == *--clean* ]]; then
  rm -rf ./_site
fi

if [[ $* == *--lint* ]]; then
  ./script/cibuild --clean
else
  rm _config_dev.yml
  cp _config.yml _config_dev.yml
  ./script/gen_img 
  python3 ./script/pyscripts/tag_gen.py
  sed -i -e 's/kevinfronczak\.com//g' _config_dev.yml
  sed -i -e 's/https\:\/\///g' _config_dev.yml
  bundle exec jekyll build --config _config_dev.yml
  bundle exec jekyll serve --config _config_dev.yml --future
fi
