#!/usr/bin/env bash
set -e
if [[ $* == *--clean* ]]; then
  rm -rf ./_site
fi

bundle exec jekyll build -d _site --future
bundle exec htmlproofer ./_site --disable-external --check-favicon --check-html --file-ignore ./_site/google2600d5f104e52ac8.html
